

# This file was *autogenerated* from the file Stage_DGA-MI_clemencem.sage
from sage.all_cmdline import *   # import sage library

_sage_const_991 = Integer(991); _sage_const_500 = Integer(500); _sage_const_300 = Integer(300); _sage_const_0 = Integer(0); _sage_const_100 = Integer(100); _sage_const_1 = Integer(1)####################
##   PARAMETRES   ##
####################

q , m , n = _sage_const_991  , _sage_const_500  , _sage_const_300  # 37 , 30 , 20 # 

test_dual = True

assert (m >= n) , 'Error parameters range : m < n'
d = m - n

# Sample A
condition = False
while not(condition):
	A0 , A1 = random_matrix( GF(q) , n) , random_matrix( GF(q) , d ,n )
	if A0.is_invertible() :
		condition = True

A = block_matrix([[A0],[A1]])
B = block_matrix([ [matrix.identity(ZZ , n) , matrix.zero(ZZ ,n ,d )] , [ (A1 * A0.inverse()).lift() , q * matrix.identity(ZZ, d) ]] )  

# q-ary lattice and associated dual and orthogonal
L = IntegralLattice(matrix.identity(d+n) , B.transpose())
L_dual = L.dual_lattice()

B_dual = matrix(QQ , L_dual.basis())
B_perp = matrix(ZZ , q * B_dual )



###########################
##   AFFICHAGE CONSOLE   ##
###########################

print('**   LWE associé à A | Réseau L associé à B ')
print('--')

"""
print('A : ')
print(A)
print('B : ')
print(B)
print('Bperp : ')
print(B_perp)
"""
# Test dual
success , T = _sage_const_0  ,_sage_const_100 
if test_dual :
	for i in range(T):
		x = random_vector(ZZ,n+d)
		w = x * B_perp
		if w in L_dual :
			success += _sage_const_1 
print('Test dual : ' , _sage_const_100  * success / T , ' %')

